"""Added user

Revision ID: 42578aded085
Revises: 4be4b00e3145
Create Date: 2020-01-14 17:35:12.667414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42578aded085'
down_revision = '4be4b00e3145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'pass_secure')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
